services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: Lab1-EMT
      POSTGRES_PASSWORD: Lab1-EMT
      POSTGRES_DB: book_rental
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - 5433:5432
volumes:
  pgdata:
